[build]
  publish = "docs"

[[redirects]]
  from = "/"
  to = "/viewer/app.html"
  status = 200

[[redirects]]
  from = "/app.html"
  to = "/viewer/app.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"
